### PR TITLE
hu translation

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
Are you able to advise why this failed?
Can this pull request still be merged?
Thank you

**Review by matfantinel — APPROVED** [review]

**Comment by matfantinel** [comment]
Hi @ovari , sorry for the delay in answering this.

Seems like the automatic builds are broken. The app is building just fine locally.
I will merge this and your translation will be available in the next release! Thanks for contributing!

**Comment by ovari** [comment]
Could you please advise when Moneta with the hu translation will be available on [Flathub](https://flathub.org/apps/details/com.github.matfantinel.moneta)?

Thank you

**Comment by ovari** [comment]
@matfantinel can Hungarian Forint (HUF) please be added to the currencies?

Does a new issue need to be created for this?

Thank you

**Comment by matfantinel** [comment]
@ovari I'll probably make a release tomorrow, and it takes around 24h for it to be available on Flathub.

About the new currency, yes, it'd be great if you opened another issue for that so I can organize myself better

**Pull request merged**
