### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
IMHO, the previous icon doesn't really look aesthetically pleasing. I designed a new one inspired by the icon of the now defunct eOS app ["Exchange"](https://appcenter.elementary.io/com.github.brandonlujan.exchange/). This is just an early draft, if you like it I'll continue the work. Feel free to give criticism as well!

### CODE REVIEW

**Comment by matfantinel** [comment]
Hey @Fatih20 , sorry for the delay answering this PR. I loved the idea of the icon, it would indeed be an improvement. I'm not a fan of the square shape though. Something like the Exchange app (with the bills being "rotated" a bit to overlap) would look nicer? I think it would make the icon more recognizable (currently some users could mistake it with a .zip file thumbnail 😆) and aesthetically pleasing.

But great job on the icon

**Comment by Fatih20** [comment]
> Hey @Fatih20 , sorry for the delay answering this PR. I loved the idea of the icon, it would indeed be an improvement. I'm not a fan of the square shape though. Something like the Exchange app (with the bills being "rotated" a bit to overlap) would look nicer? I think it would make the icon more recognizable (currently some users could mistake it with a .zip file thumbnail laughing) and aesthetically pleasing.
> 
> But great job on the icon

Haha, thanks. I'll look into it.

**Comment by matfantinel** [comment]
Some inspiration for a way to lay them out: [Palette](https://appcenter.elementary.io/com.github.cassidyjames.palette/) (although with a bit less space between them), or [Planner](https://appcenter.elementary.io/com.github.alainm23.planner/)

Or this custom HydraPaper icon on Tela icon pack:

image

**Comment by Fatih20** [comment]
I used Palette very often and I tried to transfer it to this icons. But, because money are wider than swatches in the Palette's icons, I had to reduce the rotation. Here's how it looked like.
image

**Comment by Fatih20** [comment]
The green one are meant to be dollar, the pink one are euros. and the blue one is brazilian reals.

**Comment by matfantinel** [comment]
Looks great! Yeah, it would not work with a full rotation like the one in Palette. I think all it needs now is that light gradient that elementary icons have, like Planner or the previous Moneta icon. What do you think?

**Comment by Fatih20** [comment]
> Looks great! Yeah, it would not work with a full rotation like the one in Palette. I think all it needs now is that light gradient that elementary icons have, like Planner or the previous Moneta icon. What do you think?

What light gradient?

**Comment by matfantinel** [comment]
[The "gloss" displayed here](https://elementary.io/docs/human-interface-guidelines#shadows), on the "Icon Materials" section

**Comment by Fatih20** [comment]
> [The "gloss" displayed here](https://elementary.io/docs/human-interface-guidelines#shadows), on the "Icon Materials" section

It already has but it's pretty subtle, because the base color of the money in question is pretty solid and doesn't have much gradient.

**Comment by Fatih20** [comment]
Here's the commit so you can see the files up close.

**Comment by matfantinel** [comment]
Ah, I hadn't noticed it on the smaller screenshot.
Looks great imo. I'm happy with the change.

Do you mind commiting it on the multiple sizes required?

**Comment by matfantinel** [comment]
We also need to figure out what to do with the symbolic icon inside the app. I'm pretty sure the new one would look weird in there.

**Comment by Fatih20** [comment]
> Ah, I hadn't noticed it on the smaller screenshot.
> Looks great imo. I'm happy with the change.
> 
> Do you mind commiting it on the multiple sizes required?

Yes, of course. I'll get on it.

**Comment by Fatih20** [comment]
> We also need to figure out what to do with the symbolic icon inside the app. I'm pretty sure the new one would look weird in there.

Is the color of the symbolic icon hardcoded? It's just a gray color in the svg of it.

**Comment by matfantinel** [comment]
I don't remember honestly. But I think it won't look bad if it's removed. Would look cleaner without it

**Comment by Fatih20** [comment]
Forgot to mention this, but do you need the 256 sized icon? There's a folder named it in the directory.

**Comment by matfantinel** [comment]
Uuh, I think it was used in GNOME if I'm not mistaken? Doesn't hurt to add it

**Comment by Fatih20** [comment]
Download the fork, compile it yourself, and test how the icons look in every use case before merging this, thanks!

**Comment by Fatih20** [comment]
I thought about a change in colour for the dollars. What do you think of this?

**Comment by Fatih20** [comment]
Sorry, I tested it for a bit longer and it looked weird. I'll retract the changes.

**Comment by Fatih20** [comment]
So how is it? Is it good to be merged?

**Pull request merged**
