### PR TITLE
Added money entry on left and live updation right

### PR DESCRIPTION
**Pull request by guhan29**

### CODE REVIEW

**Comment by guhan29** [comment]
Screenshot from 2021-05-08 20-26-58

**Comment by matfantinel** [comment]
This is awesome, @guhan29 , thanks a lot!

I'll have some time later today probably to review this and test it out

**Comment by guhan29** [comment]
Thanks 👍

**Comment by matfantinel** [comment]
Hey @guhan29 , I'm going to merge this into the `currency-conversion` branch. I want to work a bit on the design for this feature before I release it, but will keep most of your code. I'll let you know when this is released!

Thanks a lot!

**Comment by guhan29** [comment]
Hey @matfantinel thanks for merging my pull request :+1:

**Pull request merged**
